# generated by datamodel-codegen:
#   filename:  cdisc-library-api.json
#   timestamp: 2024-08-16T16:59:51+00:00

from __future__ import annotations

from datetime import date
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import AnyUrl, Field
from pydantic_v2 import BaseModel
from typing_extensions import Annotated


class Link(BaseModel):
    href: Annotated[Optional[AnyUrl], Field(description='href')] = None
    title: Annotated[Optional[str], Field(description='title')] = None
    type: Annotated[Optional[str], Field(description='type')] = None


class RootItemRef(Link):
    pass


class PriorVersion(RootItemRef):
    pass


class Action(BaseModel):
    name: Annotated[Optional[str], Field(description='Name of the action to take')] = (
        None
    )
    params: Annotated[
        Optional[Dict[str, Any]], Field(description='Parameters needed by the action')
    ] = None


class Condition(BaseModel):
    name: Annotated[Optional[str], Field(description='Name of the condition')] = None
    params: Annotated[
        Optional[Dict[str, Any]],
        Field(description='Parameters needed by the condition'),
    ] = None
    operator: Annotated[
        Optional[str],
        Field(description='The operator to perform on the condition method'),
    ] = None
    value: Annotated[
        Optional[Any], Field(description='Any necessary comparison value')
    ] = None
    any: Annotated[
        Optional[List[Condition]],
        Field(
            description='A list of conditions that will return true if any of the conditions in the list are true'
        ),
    ] = None
    all: Annotated[
        Optional[List[Condition]],
        Field(
            description='A list of conditions that will return try if all of the conditions in the list are true'
        ),
    ] = None


class Standard(BaseModel):
    Name: Annotated[Optional[str], Field(description='Standard type')] = None
    Version: Annotated[
        Optional[str], Field(description='standard version', example='3-4')
    ] = None


class RuleReference(BaseModel):
    Id: Annotated[Optional[str], Field(description='Published rule id')] = None
    Origin: Annotated[Optional[str], Field(description='Rule source')] = None
    Version: Annotated[Optional[str], Field(description='Rule version')] = None


class Authority(BaseModel):
    Organization: Annotated[
        Optional[str], Field(description='Publisher organization')
    ] = None


class RuleClasses(BaseModel):
    Include: Annotated[
        Optional[List[str]],
        Field(
            description="A list of classes that a rule explicitly applies to. Use 'All' when a rule applies to all classes"
        ),
    ] = None
    Exclude: Annotated[
        Optional[List[str]],
        Field(
            description='A list of classes that a rule explicitly DOES NOT apply to.'
        ),
    ] = None


class RuleDomains(BaseModel):
    Include: Annotated[
        Optional[List[str]],
        Field(
            description="A list of domains that a rule explicitly applies to. Use 'All' when a rule applies to all domains"
        ),
    ] = None
    Exclude: Annotated[
        Optional[List[str]],
        Field(
            description='A list of domains that a rule explicitly DOES NOT apply to.'
        ),
    ] = None


class FieldLinks(BaseModel):
    self: Optional[Link] = None
    package: Optional[Link] = None
    priorVersion: Optional[Link] = None
    standards: Optional[List[Link]] = None


class Rule(BaseModel):
    field_links: Annotated[Optional[FieldLinks], Field(alias='_links')] = None
    actions: Optional[List[Action]] = None
    core_id: Annotated[
        Optional[str], Field(description='Identifier for core related activities')
    ] = None
    description: Annotated[Optional[str], Field(description='Rule description')] = None
    id: Annotated[
        Optional[str], Field(description='Unique id for referencing a rule')
    ] = None
    rule_type: Annotated[Optional[str], Field(description='Type of rule')] = None
    sensitivity: Annotated[Optional[str], Field(description='Rule sensitivity')] = None
    severity: Annotated[
        Optional[str], Field(description='Describes how severe a rule violatio is')
    ] = None
    standards: Annotated[
        Optional[List[Standard]], Field(description='All standards the rule applies to')
    ] = None
    reference: Optional[RuleReference] = None
    authority: Optional[Authority] = None
    classes: Optional[RuleClasses] = None
    domains: Optional[RuleDomains] = None
    conditions: Optional[Condition] = None


class FieldLinks1(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[Link] = None
    standards: Optional[List[Link]] = None


class RulePackage(BaseModel):
    field_links: Annotated[Optional[FieldLinks1], Field(alias='_links')] = None
    rules: Annotated[
        Optional[Dict[str, Any]],
        Field(description='Mapping of rule id to rule definition'),
    ] = None


class BodyItem(BaseModel):
    format: Optional[Dict[str, Any]] = None
    text: Optional[str] = None


class DiffItem(BaseModel):
    body: Optional[List[Dict[str, List[BodyItem]]]] = None
    head: Optional[List[str]] = None
    title: Optional[str] = None


class DiffResult(BaseModel):
    diff: Optional[List[DiffItem]] = None


class FieldLinks2(BaseModel):
    self: Optional[Link] = None
    searchResults: Annotated[
        Optional[List[Link]], Field(description='Search Results')
    ] = None


class SearchResult(BaseModel):
    field_links: Annotated[Optional[FieldLinks2], Field(alias='_links')] = None


class SearchScopeList(BaseModel):
    scopes: Annotated[Optional[List[str]], Field(description='Search Scopes')] = None


class FieldLinks3(BaseModel):
    self: Optional[Link] = None
    searchResults: Annotated[
        Optional[List[Link]], Field(description='Suggestion Results')
    ] = None


class SuggestResult(BaseModel):
    field_links: Annotated[Optional[FieldLinks3], Field(alias='_links')] = None


class FieldLinks4(BaseModel):
    self: Optional[Link] = None
    versions: Annotated[Optional[List[Link]], Field(description='Item Versions')] = None


class RootItem(BaseModel):
    field_links: Annotated[Optional[FieldLinks4], Field(alias='_links')] = None


class ProductAttributes(BaseModel):
    name: Annotated[Optional[str], Field(description='Product Name')] = None
    label: Annotated[Optional[str], Field(description='Product Label')] = None
    description: Annotated[Optional[str], Field(description='Product Description')] = (
        None
    )
    source: Annotated[Optional[str], Field(description='Product Source')] = None
    effectiveDate: Annotated[Optional[date], Field(description='Effective Date')] = None
    registrationStatus: Annotated[
        Optional[str], Field(description='Registration Status')
    ] = None
    version: Annotated[Optional[str], Field(description='Version')] = None


class ProductRef(RootItemRef):
    pass


class CorrigendaItem(BaseModel):
    impactedItem: Annotated[Optional[Link], Field(description='Impacted Item')] = None
    impactedProperty: Annotated[
        Optional[str], Field(description='Impacted Property')
    ] = None
    publishedValue: Annotated[Optional[str], Field(description='Published Value')] = (
        None
    )
    correctedValue: Annotated[Optional[str], Field(description='Corrected Value')] = (
        None
    )
    publishedResource: Annotated[
        Optional[Link], Field(description='Published Resource Reference')
    ] = None
    correctedResource: Annotated[
        Optional[Link], Field(description='Corrected Resource Reference')
    ] = None


class Corrigenda(BaseModel):
    __root__: Annotated[List[CorrigendaItem], Field(description='List of Corrigenda')]


class ParentPackage(RootItemRef):
    pass


class ParentCodelist(RootItemRef):
    pass


class TermRef(RootItemRef):
    pass


class CodelistRef(RootItemRef):
    pass


class PackageRef(RootItemRef):
    pass


class FieldLinks5(BaseModel):
    self: Optional[Link] = None
    parentPackage: Optional[ParentPackage] = None
    parentCodelist: Optional[ParentCodelist] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None


class Term(BaseModel):
    conceptId: Annotated[
        Optional[str],
        Field(description='NCI Thesaurus Concept Identifier', regex='C\\d+$'),
    ] = None
    submissionValue: Annotated[
        Optional[str], Field(description='Term Submission Value')
    ] = None
    definition: Annotated[Optional[str], Field(description='Term Definition')] = None
    preferredTerm: Annotated[Optional[str], Field(description='Preferred Term')] = None
    synonyms: Annotated[Optional[List[str]], Field(description='Term Synonyms')] = None
    field_links: Annotated[Optional[FieldLinks5], Field(alias='_links')] = None


class PackageTerm(BaseModel):
    conceptId: Annotated[
        Optional[str],
        Field(description='NCI Thesaurus Concept Identifier', regex='C\\d+$'),
    ] = None
    submissionValue: Annotated[
        Optional[str], Field(description='Term Submission Value')
    ] = None
    definition: Annotated[Optional[str], Field(description='Term Definition')] = None
    preferredTerm: Annotated[Optional[str], Field(description='Preferred Term')] = None
    synonyms: Annotated[Optional[List[str]], Field(description='Term Synonyms')] = None


class CodelistAttributes(BaseModel):
    conceptId: Annotated[
        Optional[str],
        Field(description='NCI Thesaurus Concept Identifier', regex='C\\d+$'),
    ] = None
    extensible: Annotated[Optional[bool], Field(description='Extensible')] = None
    name: Annotated[Optional[str], Field(description='Codelist Name')] = None
    submissionValue: Annotated[
        Optional[str], Field(description='Codelist Submission Value')
    ] = None
    definition: Annotated[Optional[str], Field(description='Codelist Definition')] = (
        None
    )
    preferredTerm: Annotated[
        Optional[str], Field(description='Codelist Preferred Term')
    ] = None
    synonyms: Annotated[Optional[List[str]], Field(description='Codelist Synonyms')] = (
        None
    )


class FieldLinks6(BaseModel):
    self: Optional[Link] = None
    parentPackage: Optional[ParentPackage] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None


class Codelist(CodelistAttributes):
    field_links: Annotated[Optional[FieldLinks6], Field(alias='_links')] = None
    terms: Annotated[
        Optional[List[PackageTerm]], Field(description='Codelist Terms')
    ] = None


class PackageCodelist(CodelistAttributes):
    terms: Annotated[
        Optional[List[PackageTerm]], Field(description='Codelist Terms')
    ] = None


class FieldLinks7(BaseModel):
    self: Optional[Link] = None
    parentPackage: Optional[ParentPackage] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None
    terms: Annotated[
        Optional[List[TermRef]], Field(description='Codelist Term References')
    ] = None


class CodelistDigest(CodelistAttributes):
    field_links: Annotated[Optional[FieldLinks7], Field(alias='_links')] = None


class FieldLinks8(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None


class Package(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks8], Field(alias='_links')] = None
    codelists: Annotated[
        Optional[List[PackageCodelist]], Field(description='Codelists')
    ] = None


class FieldLinks9(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    codelists: Annotated[
        Optional[List[CodelistRef]], Field(description='Codelist References')
    ] = None


class PackageDigest(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks9], Field(alias='_links')] = None


class FieldLinks10(BaseModel):
    self: Optional[Link] = None
    packages: Annotated[
        Optional[List[PackageRef]], Field(description='Package References')
    ] = None


class PackageList(BaseModel):
    field_links: Annotated[Optional[FieldLinks10], Field(alias='_links')] = None


class ValuelistRef(RootItemRef):
    pass


class ModelRef(RootItemRef):
    pass


class ClassRef(RootItemRef):
    pass


class ClassAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Class Name')] = None
    label: Annotated[Optional[str], Field(description='Class Label')] = None
    description: Annotated[Optional[str], Field(description='Class Description')] = None


class FieldRef(RootItemRef):
    pass


class DomainRef(RootItemRef):
    pass


class ScenarioRef(RootItemRef):
    pass


class CdashFieldAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Field Name')] = None
    label: Annotated[Optional[str], Field(description='Field Label')] = None
    definition: Annotated[Optional[str], Field(description='Field Definition')] = None
    questionText: Annotated[Optional[str], Field(description='Field Question Text')] = (
        None
    )
    prompt: Annotated[Optional[str], Field(description='Field Prompt')] = None
    completionInstructions: Annotated[
        Optional[str], Field(description='Field Completion Instructions')
    ] = None
    implementationNotes: Annotated[
        Optional[str], Field(description='Field Implementation Notes')
    ] = None
    simpleDatatype: Annotated[
        Optional[str], Field(description='Field Simple Datatype')
    ] = None
    mappingInstructions: Annotated[
        Optional[str], Field(description='Field Mapping Instructions')
    ] = None


class CdashModelFieldAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Field Name')] = None
    label: Annotated[Optional[str], Field(description='Field Label')] = None
    definition: Annotated[Optional[str], Field(description='Field Definition')] = None
    domainSpecific: Annotated[Optional[bool], Field(description='Domain-Specific')] = (
        None
    )
    questionText: Annotated[Optional[str], Field(description='Field Question Text')] = (
        None
    )
    prompt: Annotated[Optional[str], Field(description='Field Prompt')] = None
    implementationNotes: Annotated[
        Optional[str], Field(description='Field Implementation Notes')
    ] = None
    simpleDatatype: Annotated[
        Optional[str], Field(description='Field Simple Datatype')
    ] = None
    mappingInstructions: Annotated[
        Optional[str], Field(description='Field Mapping Instructions')
    ] = None


class FieldLinks12(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None


class FieldLinks13(FieldLinks8):
    pass


class FieldLinks14(FieldLinks12):
    pass


class CdashDomainAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Domain Name')] = None
    label: Annotated[Optional[str], Field(description='Domain Label')] = None
    status: Annotated[Optional[str], Field(description='Domain Status')] = None


class FieldLinks16(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    classes: Annotated[
        Optional[List[ClassRef]], Field(description='Class References')
    ] = None


class ClassList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks16], Field(alias='_links')] = None


class FieldLinks17(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    classes: Annotated[
        Optional[List[ClassRef]], Field(description='Class References')
    ] = None


class CdashClassList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks17], Field(alias='_links')] = None


class FieldLinks18(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None


class CdashDomainList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks18], Field(alias='_links')] = None
    domains: Annotated[
        Optional[List[DomainRef]], Field(description='Domain Reference List')
    ] = None


class FieldLinks19(BaseModel):
    self: Optional[Link] = None


class CdashClassDomainList(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks19], Field(alias='_links')] = None
    domains: Annotated[
        Optional[List[DomainRef]], Field(description='Domain Reference List')
    ] = None


class FieldLinks20(FieldLinks12):
    pass


class CdashFieldList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks20], Field(alias='_links')] = None
    fields: Annotated[
        Optional[List[FieldRef]], Field(description='Field Reference List')
    ] = None


class CdashigDomainAttributes(CdashDomainAttributes):
    pass


class FieldLinks23(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None
    scenarios: Annotated[
        Optional[List[ScenarioRef]], Field(description='Domain Scenarios')
    ] = None


class FieldLinks24(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None
    fields: Annotated[
        Optional[List[FieldRef]], Field(description='Domain Field References')
    ] = None


class CdashigDomainDigest(CdashigDomainAttributes):
    field_links: Annotated[Optional[FieldLinks24], Field(alias='_links')] = None


class CdashigScenarioAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    domain: Annotated[Optional[str], Field(description='Domain')] = None
    domainName: Annotated[
        Optional[str], Field(description='Two character domain name')
    ] = None
    scenario: Annotated[Optional[str], Field(description='Scenario')] = None


class FieldLinks25(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    parentDomain: Optional[DomainRef] = None
    priorVersion: Optional[PriorVersion] = None


class FieldLinks26(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    parentDomain: Optional[DomainRef] = None
    priorVersion: Optional[PriorVersion] = None
    fields: Annotated[
        Optional[List[FieldRef]], Field(description='CDASHIG Field References')
    ] = None


class CdashigScenarioDigest(CdashigScenarioAttributes):
    field_links: Annotated[Optional[FieldLinks26], Field(alias='_links')] = None


class FieldLinks27(BaseModel):
    self: Optional[Link] = None
    modelClass: Optional[ClassRef] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    subclasses: Optional[List[ClassRef]] = None
    priorVersion: Optional[PriorVersion] = None


class FieldLinks28(BaseModel):
    self: Optional[Link] = None
    domains: Annotated[
        Optional[List[DomainRef]], Field(description='Domain References')
    ] = None


class ClassDomainList(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks28], Field(alias='_links')] = None


class FieldLinks29(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    scenarios: Annotated[
        Optional[List[ScenarioRef]], Field(description='Scenario References')
    ] = None


class ClassScenarioList(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks29], Field(alias='_links')] = None


class FieldLinks30(BaseModel):
    self: Optional[Link] = None
    model: Optional[ModelRef] = None
    priorVersion: Optional[PriorVersion] = None


class FieldLinks31(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    domains: Annotated[
        Optional[List[DomainRef]], Field(description='Domain References')
    ] = None


class CdashigDomainList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks31], Field(alias='_links')] = None


class FieldLinks32(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    scenarios: Annotated[
        Optional[List[ScenarioRef]], Field(description='Scenario References')
    ] = None


class CdashigScenarioList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks32], Field(alias='_links')] = None


class VariableRef(RootItemRef):
    pass


class QualifiesVariableRef(RootItemRef):
    pass


class DatasetRef(RootItemRef):
    pass


class SdtmVariableAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Variable Name')] = None
    label: Annotated[Optional[str], Field(description='Variable Label')] = None
    description: Annotated[Optional[str], Field(description='Variable Description')] = (
        None
    )
    role: Annotated[Optional[str], Field(description='Variable Role')] = None
    roleDescription: Annotated[
        Optional[str], Field(description='Variable Role Description')
    ] = None
    simpleDatatype: Annotated[
        Optional[str], Field(description='Variable Simple Datatype')
    ] = None
    usageRestrictions: Annotated[
        Optional[str], Field(description='Variable Usage Restrictions')
    ] = None
    notes: Annotated[Optional[str], Field(description='Variable Notes')] = None
    examples: Annotated[Optional[str], Field(description='Variable examples')] = None


class FieldLinks33(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentDataset: Optional[DatasetRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None


class DatasetVariable(SdtmVariableAttributes):
    field_links: Annotated[Optional[FieldLinks33], Field(alias='_links')] = None


class DatasetAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Dataset Name')] = None
    label: Annotated[Optional[str], Field(description='Dataset Label')] = None
    description: Annotated[Optional[str], Field(description='Dataset Description')] = (
        None
    )
    datasetStructure: Annotated[
        Optional[str], Field(description='Dataset Structure')
    ] = None
    status: Annotated[Optional[str], Field(description='Dataset Status')] = None


class FieldLinks34(FieldLinks12):
    pass


class Dataset(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks34], Field(alias='_links')] = None
    datasetVariables: Annotated[
        Optional[List[DatasetVariable]], Field(description='Dataset Variables')
    ] = None


class FieldLinks35(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None
    datasetVariables: Annotated[
        Optional[List[VariableRef]], Field(description='Dataset Variable References')
    ] = None


class DatasetDigest(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks35], Field(alias='_links')] = None


class FieldLinks36(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    qualifiesVariables: Annotated[
        Optional[List[QualifiesVariableRef]],
        Field(description='Variables qualified by this variable'),
    ] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None


class ClassVariable(SdtmVariableAttributes):
    field_links: Annotated[Optional[FieldLinks36], Field(alias='_links')] = None


class FieldLinks37(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    subclasses: Optional[List[ClassRef]] = None
    priorVersion: Optional[PriorVersion] = None


class SdtmClass(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks37], Field(alias='_links')] = None
    classVariables: Annotated[
        Optional[List[ClassVariable]], Field(description='Class Variables')
    ] = None
    datasets: Annotated[Optional[List[Dataset]], Field(description='Datasets')] = None


class FieldLinks38(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    classVariables: Annotated[
        Optional[List[VariableRef]], Field(description='Class Variable References')
    ] = None


class ClassVariableList(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks38], Field(alias='_links')] = None


class FieldLinks39(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    datasets: Annotated[
        Optional[List[DatasetRef]], Field(description='Dataset References')
    ] = None


class ClassDatasetList(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks39], Field(alias='_links')] = None


class FieldLinks40(FieldLinks8):
    pass


class SdtmProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks40], Field(alias='_links')] = None
    classes: Annotated[Optional[List[SdtmClass]], Field(description='Classes')] = None


class FieldLinks41(FieldLinks39):
    pass


class DataTabulationDatasetList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks41], Field(alias='_links')] = None


class FieldLinks42(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    modelDatasetVariable: Optional[VariableRef] = None
    parentProduct: Optional[ProductRef] = None
    parentDataset: Optional[DatasetRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None


class IgVariableAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Variable Name')] = None
    label: Annotated[Optional[str], Field(description='Variable Label')] = None
    description: Annotated[Optional[str], Field(description='Variable Description')] = (
        None
    )
    role: Annotated[Optional[str], Field(description='Variable Role')] = None
    simpleDatatype: Annotated[
        Optional[str], Field(description='Variable Simple Datatype')
    ] = None
    core: Annotated[Optional[str], Field(description='Core Classifier')] = None
    describedValueDomain: Annotated[
        Optional[str], Field(description='Described Value Domain')
    ] = None
    valueList: Annotated[Optional[List[str]], Field(description='Value List')] = None
    field_links: Annotated[Optional[FieldLinks42], Field(alias='_links')] = None


class SdtmigVariable(IgVariableAttributes):
    pass


class FieldLinks43(BaseModel):
    self: Optional[Link] = None
    modelDataset: Optional[DatasetRef] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None


class SdtmigDataset(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks43], Field(alias='_links')] = None
    datasetVariables: Annotated[
        Optional[List[SdtmigVariable]], Field(description='Dataset Variables')
    ] = None


class FieldLinks44(BaseModel):
    self: Optional[Link] = None
    modelDataset: Optional[DatasetRef] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    priorVersion: Optional[PriorVersion] = None
    datasetVariables: Annotated[
        Optional[List[VariableRef]], Field(description='Dataset Variable References')
    ] = None


class SdtmigDatasetDigest(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks44], Field(alias='_links')] = None


class FieldLinks45(FieldLinks27):
    pass


class SdtmigClass(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks45], Field(alias='_links')] = None
    datasets: Annotated[
        Optional[List[SdtmigDataset]], Field(description='Datasets')
    ] = None


class FieldLinks46(FieldLinks30):
    pass


class SdtmigProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks46], Field(alias='_links')] = None
    classes: Annotated[Optional[List[SdtmigClass]], Field(description='Classes')] = None


class SendigVariable(SdtmigVariable):
    pass


class FieldLinks47(FieldLinks43):
    pass


class SendigDataset(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks47], Field(alias='_links')] = None
    datasetVariables: Annotated[
        Optional[List[SendigVariable]], Field(description='Dataset Variables')
    ] = None


class FieldLinks48(FieldLinks44):
    pass


class SendigDatasetDigest(DatasetAttributes):
    field_links: Annotated[Optional[FieldLinks48], Field(alias='_links')] = None


class FieldLinks49(FieldLinks27):
    pass


class SendigClass(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks49], Field(alias='_links')] = None
    datasets: Annotated[
        Optional[List[SendigDataset]], Field(description='Datasets')
    ] = None


class FieldLinks50(FieldLinks30):
    pass


class SendigProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks50], Field(alias='_links')] = None
    classes: Annotated[Optional[List[SendigClass]], Field(description='Classes')] = None


class AnalysisVariableRef(RootItemRef):
    pass


class AnalysisVariableSetRef(RootItemRef):
    pass


class AnalysisDatastructureRef(RootItemRef):
    pass


class Core(Enum):
    Perm = 'Perm'
    Req = 'Req'
    Cond = 'Cond'


class FieldLinks51(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    valuelist: Optional[ValuelistRef] = None
    parentProduct: Optional[ProductRef] = None
    parentDatastructure: Optional[AnalysisDatastructureRef] = None
    parentVariableSet: Optional[AnalysisVariableSetRef] = None
    parentClassVariable: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None


class AnalysisVariable(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Analysis Variable Name')] = None
    label: Annotated[Optional[str], Field(description='Analysis Variable Label')] = None
    description: Annotated[
        Optional[str], Field(description='Analysis Variable Description')
    ] = None
    core: Annotated[Optional[Core], Field(description='Core Classifier')] = None
    simpleDatatype: Annotated[
        Optional[str], Field(description='Analysis Variable Simple Datatype')
    ] = None
    valueList: Annotated[Optional[List[str]], Field(description='Value List')] = None
    field_links: Annotated[Optional[FieldLinks51], Field(alias='_links')] = None


class FieldLinks52(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    parentDatastructure: Optional[AnalysisDatastructureRef] = None
    priorVersion: Optional[PriorVersion] = None
    parentClassVariableSet: Optional[AnalysisVariableSetRef] = None


class AnalysisVariableSet(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Analysis Variable Set Name')] = (
        None
    )
    label: Annotated[
        Optional[str], Field(description='Analysis Variable Set Label')
    ] = None
    field_links: Annotated[Optional[FieldLinks52], Field(alias='_links')] = None
    analysisVariables: Annotated[
        Optional[List[AnalysisVariable]], Field(description='Analysis Variables')
    ] = None


class AnalysisDatastructureAttributes(BaseModel):
    ordinal: Annotated[Optional[int], Field(description='Ordinal')] = None
    name: Annotated[Optional[str], Field(description='Datastructure Name')] = None
    label: Annotated[Optional[str], Field(description='Datastructure Label')] = None
    description: Annotated[
        Optional[str], Field(description='Datastructure Description')
    ] = None
    class_: Annotated[
        Optional[str], Field(alias='class', description='Datastructure Class')
    ] = None
    subClass: Annotated[Optional[str], Field(description='Datastructure Sub class')] = (
        None
    )
    status: Annotated[Optional[str], Field(description='Datastructure Status')] = None


class FieldLinks53(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    parentClassDatastructure: Optional[AnalysisDatastructureRef] = None


class AnalysisDatastructure(AnalysisDatastructureAttributes):
    field_links: Annotated[Optional[FieldLinks53], Field(alias='_links')] = None
    analysisVariableSets: Annotated[
        Optional[List[AnalysisVariableSet]], Field(description='Analysis Variable Sets')
    ] = None


class FieldLinks54(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    analysisVariableSets: Annotated[
        Optional[List[AnalysisVariableSet]],
        Field(description='Analysis Variable Set References'),
    ] = None


class AnalysisVariableSetList(AnalysisDatastructureAttributes):
    field_links: Annotated[Optional[FieldLinks54], Field(alias='_links')] = None


class FieldLinks55(BaseModel):
    self: Optional[Link] = None
    parentProduct: Optional[ProductRef] = None
    priorVersion: Optional[PriorVersion] = None
    analysisVariables: Annotated[
        Optional[List[AnalysisVariableRef]],
        Field(description='Analysis Variable References'),
    ] = None


class AnalysisVariableList(AnalysisDatastructureAttributes):
    field_links: Annotated[Optional[FieldLinks55], Field(alias='_links')] = None


class FieldLinks56(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    datastructures: Annotated[
        Optional[List[AnalysisDatastructureRef]],
        Field(description='Datastructure References'),
    ] = None


class AnalysisDatastructureList(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks56], Field(alias='_links')] = None


class FieldLinks57(FieldLinks8):
    pass


class AdamProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks57], Field(alias='_links')] = None
    dataStructures: Annotated[
        Optional[List[AnalysisDatastructure]],
        Field(description='Analysis Variable Sets'),
    ] = None


class Standards(BaseModel):
    sdtmig: Optional[Link] = None
    cdashig: Optional[Link] = None
    sendig: Optional[Link] = None
    adamig: Optional[Link] = None


class FieldLinks58(BaseModel):
    self: Optional[Link] = None
    priorVersion: Optional[PriorVersion] = None
    standards: Optional[Standards] = None
    models: Optional[List[Link]] = None


class IntegratedStandard(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks58], Field(alias='_links')] = None


class ProductgroupRef(BaseModel):
    href: Annotated[Optional[str], Field(example='/mdr/products/QrsInstrument')] = None
    title: Annotated[Optional[str], Field(example='Product Group QRS Instrument')] = (
        None
    )
    type: Annotated[Optional[str], Field(example='CDISC Library Product Group')] = None


class QrsInstrumentRefElement(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/qrs/instruments/AIMS01/versions/1-0')
    ] = None
    title: Annotated[
        Optional[str], Field(example='Abnormal Involuntary Movement Scale Version 1.0')
    ] = None
    type: Annotated[Optional[str], Field(example='QRS Instrument')] = None


class QrsInstrumentProductRef(QrsInstrumentRefElement):
    pass


class QrsInstrumentResponseGroupsRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/qrs/instruments/AMS01/versions/1-0/responseGroups'),
    ] = None
    title: Annotated[
        Optional[str], Field(example='QRS Instrument Response Groups for AMS01 v1.0')
    ] = None
    type: Annotated[Optional[str], Field(example='QRS Instrument Response Groups')] = (
        None
    )


class QrsInstrumentResponseGroupRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/qrs/instruments/AMS01/versions/1-0/responseGroups/AIMS01-01_to_07'
        ),
    ] = None
    title: Annotated[
        Optional[str],
        Field(example='QRS Instrument Response Group AIMS01-01 to 07 for AMS01 v1.0'),
    ] = None
    type: Annotated[Optional[str], Field(example='QRS Instrument Response Group')] = (
        None
    )


class QrsInstrumentItemsRef(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/qrs/instruments/AMS01/versions/1-0/items')
    ] = None
    title: Annotated[
        Optional[str], Field(example='QRS Instrument Items for AMS01 v1.0')
    ] = None
    type: Annotated[Optional[str], Field(example='QRS Instrument Response Items')] = (
        None
    )


class QrsInstrumentItemRef(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/qrs/instruments/AMS01/versions/1-0/items/1')
    ] = None
    title: Annotated[
        Optional[str], Field(example='QRS Instrument Item 1 for AMS01 v1.0')
    ] = None
    type: Annotated[Optional[str], Field(example='QRS Instrument Item')] = None


class Self(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/root/qrs/instruments/AIMS01')
    ] = None
    title: Annotated[
        Optional[str],
        Field(example='Version-agnostic anchor element for QRS Intrument AIMS01'),
    ] = None
    type: Annotated[Optional[str], Field(example='Root QRS Instrument')] = None


class FieldLinks62(BaseModel):
    self: Optional[Self] = None
    versions: Optional[List[QrsInstrumentProductRef]] = None


class RootQrsInstrument(BaseModel):
    field_links: Annotated[Optional[FieldLinks62], Field(alias='_links')] = None


class RootTermInstrumentCATRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C118971/terms/C102111'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C118971.C102111'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermInstrumentSCATRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C222222/terms/C333333'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C222222.C333333'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermInstrumentItemTESTCDRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C101805/terms/C102034'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C101805.C102034'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermInstrumentItemTESTRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C101806/terms/C102034'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C101806.C102034'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermResponseORRESRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C135012/terms/C28077'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C135012.C28077'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermResponseSTRESCRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/root/ct/sdtmct/codelists/C160923/terms/C161425'),
    ] = None
    title: Annotated[
        Optional[str],
        Field(
            example='Version-agnostic anchor resource for codelist term C160923.C161425'
        ),
    ] = None
    type: Annotated[Optional[str], Field(example='Root Value')] = None


class RootTermResponseSTRESNRef(RootTermResponseSTRESCRef):
    pass


class LastupdatedAttributes(BaseModel):
    overall: Annotated[
        Optional[str], Field(description='Last Updated Date for Overall CDISC Library')
    ] = None
    data_analysis: Annotated[
        Optional[str],
        Field(
            alias='data-analysis',
            description='Last Updated Date for Data Analysis Products',
        ),
    ] = None
    data_collection: Annotated[
        Optional[str],
        Field(
            alias='data-collection',
            description='Last Updated Date for Data Collection Products',
        ),
    ] = None
    data_tabulation: Annotated[
        Optional[str],
        Field(
            alias='data-tabulation',
            description='Last Updated Date for Data Tabulation Products',
        ),
    ] = None
    qrs: Annotated[
        Optional[str],
        Field(description='Last Updated Date for QRS instrument Products'),
    ] = None
    terminology: Annotated[
        Optional[str], Field(description='Last Updated Date for Terminology Products')
    ] = None


class FieldLinks63(FieldLinks19):
    pass


class Lastupdated(LastupdatedAttributes):
    field_links: Annotated[Optional[FieldLinks63], Field(alias='_links')] = None


class MaintenanceAttributes(BaseModel):
    maintenanceMode: Annotated[Optional[str], Field(description='Maintenance mode')] = (
        None
    )
    maintenanceMessage: Annotated[
        Optional[str], Field(description='Maintenance message')
    ] = None


class Maintenance(MaintenanceAttributes):
    pass


class AboutAttributes(BaseModel):
    release_notes: Annotated[
        Optional[str],
        Field(alias='release-notes', description='URL to CDISC Library Release Notes'),
    ] = None
    api_documentation: Annotated[
        Optional[str],
        Field(
            alias='api-documentation',
            description='URL to CDISC Library API Documentation',
        ),
    ] = None


class About(AboutAttributes):
    field_links: Annotated[Optional[FieldLinks63], Field(alias='_links')] = None


class FieldLinks66(BaseModel):
    self: Optional[Link] = None
    packages: Optional[List[Link]] = None


class ProductTerminology(BaseModel):
    field_links: Annotated[Optional[FieldLinks66], Field(alias='_links')] = None


class FieldLinks67(BaseModel):
    self: Optional[Link] = None
    adam: Optional[List[Link]] = None


class ProductDataAnalysis(BaseModel):
    field_links: Annotated[Optional[FieldLinks67], Field(alias='_links')] = None


class FieldLinks68(BaseModel):
    self: Optional[Link] = None
    sdtm: Optional[List[Link]] = None
    sdtmig: Optional[List[Link]] = None
    sendig: Optional[List[Link]] = None


class ProductDataTabulation(BaseModel):
    field_links: Annotated[Optional[FieldLinks68], Field(alias='_links')] = None


class FieldLinks69(BaseModel):
    self: Optional[Link] = None
    cdash: Optional[List[Link]] = None
    cdashig: Optional[List[Link]] = None


class ProductDataCollection(BaseModel):
    field_links: Annotated[Optional[FieldLinks69], Field(alias='_links')] = None


class FieldLinks70(BaseModel):
    self: Optional[Link] = None
    instrument: Optional[List[Link]] = None


class ProductQrsInstrument(BaseModel):
    field_links: Annotated[Optional[FieldLinks70], Field(alias='_links')] = None


class FieldLinks71(BaseModel):
    self: Optional[Link] = None
    cdash: Optional[List[Link]] = None
    cdashig: Optional[List[Link]] = None
    sdtm: Optional[List[Link]] = None
    sdtmig: Optional[List[Link]] = None
    sendig: Optional[List[Link]] = None
    adam: Optional[List[Link]] = None
    qrs: Optional[List[Link]] = None


class ProductDraftContent(BaseModel):
    field_links: Annotated[Optional[FieldLinks71], Field(alias='_links')] = None


class FieldLinks72(FieldLinks19):
    pass


class ProductIntegrated(BaseModel):
    field_links: Annotated[Optional[FieldLinks72], Field(alias='_links')] = None


class ProductGroupIntegrated(ProductIntegrated):
    pass


class ProductGroupDataCollection(ProductDataCollection):
    pass


class ProductGroupDataTabulation(ProductDataTabulation):
    pass


class ProductGroupDataAnalysis(ProductDataAnalysis):
    pass


class ProductGroupTerminology(ProductTerminology):
    pass


class ProductgroupQrsInstrument(ProductQrsInstrument):
    pass


class ProductGroupDraftContent(ProductDraftContent):
    pass


class FieldLinks73(BaseModel):
    self: Optional[Link] = None
    catalogs: Optional[Dict[str, Any]] = None


class RulePackageLinks(BaseModel):
    field_links: Annotated[Optional[FieldLinks73], Field(alias='_links')] = None


class FieldLinks74(BaseModel):
    self: Optional[Link] = None
    children: Optional[List[Link]] = None
    section: Optional[Link] = None
    parentProduct: Optional[Link] = None
    parentDocument: Optional[Link] = None


class IgDocument(BaseModel):
    field_links: Annotated[Optional[FieldLinks74], Field(alias='_links')] = None
    children: Optional[List[str]] = None
    createdAt: Optional[str] = None
    html: Optional[str] = None
    id: Optional[str] = None
    pageId: Optional[str] = None
    parent: Optional[str] = None
    section: Optional[str] = None
    standard: Optional[str] = None
    structures: Optional[List[str]] = None
    text: Optional[str] = None
    title: Optional[str] = None
    updatedAt: Optional[str] = None
    version: Optional[str] = None


class FieldLinks75(BaseModel):
    self: Optional[Link] = None
    sections: Optional[List[Link]] = None


class DocumentSections(BaseModel):
    field_links: Annotated[Optional[FieldLinks75], Field(alias='_links')] = None
    sections: Optional[List[str]] = None


class FieldLinks76(FieldLinks19):
    pass


class UseCaseSectionDocuments(BaseModel):
    field_links: Annotated[Optional[FieldLinks76], Field(alias='_links')] = None
    documents: Optional[List[IgDocument]] = None


class UseCase(BaseModel):
    field_links: Annotated[Optional[FieldLinks76], Field(alias='_links')] = None
    name: Optional[str] = None


class SectionsListForUsecaseAndStandard(BaseModel):
    field_links: Annotated[Optional[FieldLinks76], Field(alias='_links')] = None
    name: Annotated[Optional[str], Field(example='Diagrams')] = None


class DocumentsList(UseCaseSectionDocuments):
    pass


class Error(BaseModel):
    statusCode: Annotated[Optional[str], Field(description='HTTP Status Code')] = None
    reasonPhrase: Annotated[Optional[str], Field(description='HTTP Reason Phrase')] = (
        None
    )
    userMessage: Annotated[Optional[str], Field(description='User Error Message')] = (
        None
    )
    adminMessage: Annotated[Optional[str], Field(description='Admin Error Message')] = (
        None
    )


class BcPackagesRef(BaseModel):
    href: Annotated[Optional[str], Field(example='/mdr/bc/packages')] = None
    title: Annotated[
        Optional[str], Field(example='Product Group Biomedical Concepts')
    ] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept Package List')] = (
        None
    )


class BcPackageRef(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/bc/packages/2022-10-26/biomedicalconcepts')
    ] = None
    title: Annotated[
        Optional[str], Field(example='Biomedical Concept Package Effective 2022-10-26')
    ] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept Package')] = None


class BcBiomedicalConceptsRef(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/bc/packages/2022-10-26/biomedicalconcepts')
    ] = None
    title: Annotated[Optional[str], Field(example='Biomedical Concepts')] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept List')] = None


class BcBiomedicalConceptRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/bc/packages/2022-10-26/biomedicalconcepts/C49676'),
    ] = None
    title: Annotated[Optional[str], Field(example='Pulse Rate')] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept')] = None


class ResultScale(Enum):
    Quantitative = 'Quantitative'
    Ordinal = 'Ordinal'
    Nominal = 'Nominal'
    Narrative = 'Narrative'


class BcBiomedicalConceptParentRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/bc/packages/2022-10-26/biomedicalconcepts/C49672'),
    ] = None
    title: Annotated[Optional[str], Field(example='Vital Signs Measurement')] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept')] = None


class BcBiomedicalConceptCoding(BaseModel):
    code: Annotated[str, Field(example='39156-5')]
    system: Annotated[str, Field(example='http://loinc.org/')]
    systemName: Annotated[Optional[str], Field(example='LOINC')] = None


class BcDataElementConceptElement(BaseModel):
    conceptId: Annotated[str, Field(example='C123975')]
    href: Annotated[
        Optional[AnyUrl],
        Field(
            example='https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C123975'
        ),
    ] = None
    shortName: Annotated[Optional[str], Field(example='Vital Signs Laterality')] = None
    dataType: Annotated[Optional[str], Field(example='string')] = None
    exampleSet: Annotated[Optional[List[str]], Field(example=['Left', 'Right'])] = None


class BcDataElementConceptsRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/bc/packages/2022-10-26/biomedicalconcepts/C49676/dataelementconcepts'
        ),
    ] = None
    title: Annotated[
        Optional[str], Field(example='Pulse Rate Data Element Concept List')
    ] = None
    type: Annotated[Optional[str], Field(example='Data Element Concept List')] = None


class BcDataElementConceptRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/bc/packages/2022-10-26/biomedicalconcepts/C49676/dataelementconcepts/C123975'
        ),
    ] = None
    title: Annotated[
        Optional[str], Field(example='Vital Signs Laterality (Pulse Rate)')
    ] = None
    type: Annotated[Optional[str], Field(example='Data Element Concept')] = None


class BcDataElementConceptLinks(BaseModel):
    field_self: Annotated[Optional[BcDataElementConceptRef], Field(alias='_self')] = (
        None
    )
    biomedicalConcept: Optional[BcBiomedicalConceptRef] = None
    parentPackage: Optional[BcPackageRef] = None


class SdtmPackagesRef(BaseModel):
    href: Annotated[
        Optional[str], Field(example='/mdr/specializations/sdtm/packages')
    ] = None
    title: Annotated[
        Optional[str], Field(example='Product Group SDTM Dataset Specializations')
    ] = None
    type: Annotated[
        Optional[str], Field(example='SDTM Dataset Specialization Package List')
    ] = None


class SdtmPackageRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/specializations/sdtm/packages/2022-10-26/datasetspecializations'
        ),
    ] = None
    title: Annotated[
        Optional[str],
        Field(example='SDTM Dataset Specialization Package Effective 2022-10-26'),
    ] = None
    type: Annotated[
        Optional[str], Field(example='SDTM Dataset Specialization Package')
    ] = None


class SdtmDatasetSpecializationsRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/specializations/sdtm/packages/2022-10-26/datasetspecializations'
        ),
    ] = None
    title: Annotated[Optional[str], Field(example='SDTM Dataset Specializations')] = (
        None
    )
    type: Annotated[
        Optional[str], Field(example='SDTM Dataset Specialization List')
    ] = None


class SdtmDatasetSpecializationRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/specializations/sdtm/packages/2022-10-26/datasetspecializations/SYSBP'
        ),
    ] = None
    title: Annotated[Optional[str], Field(example='Systolic Blood Pressure')] = None
    type: Annotated[Optional[str], Field(example='SDTM Dataset Specialization')] = None


class SdtmBiomedicalConceptRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(example='/mdr/bc/packages/2022-10-26/biomedicalconcepts/C25298'),
    ] = None
    title: Annotated[Optional[str], Field(example='Systolic Blood Pressure')] = None
    type: Annotated[Optional[str], Field(example='Biomedical Concept')] = None


class SdtmDatasetpecializationRelationship(BaseModel):
    subject: Annotated[str, Field(example='VSSTRESU')]
    linkingPhrase: Annotated[
        Optional[str], Field(example='is the unit for the value in')
    ] = None
    predicateTerm: Annotated[str, Field(example='IS_UNIT_FOR')]
    object: Annotated[str, Field(example='VSSTRESN')]


class SdtmDatasetpecializationAssignedTerm(BaseModel):
    conceptId: Annotated[Optional[str], Field(example='C49670')] = None
    value: Annotated[str, Field(example='mmHG')]


class SdtmDatasetSpecializationCodeList(BaseModel):
    conceptId: Annotated[str, Field(example='C66770')]
    href: Annotated[
        Optional[AnyUrl],
        Field(
            example='https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C66770'
        ),
    ] = None
    submissionValue: Annotated[str, Field(example='VSRESU')]


class SdtmDatasetSpecializationVariablesRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/specializations/sdtm/packages/2022-10-26/datasetspecializations/SYSBP/variables'
        ),
    ] = None
    title: Annotated[
        Optional[str], Field(example='Systolic Blood Pressure Variables')
    ] = None
    type: Annotated[
        Optional[str], Field(example='SDTM Dataset Specialization Variables')
    ] = None


class SdtmDatasetSpecializationVariableRef(BaseModel):
    href: Annotated[
        Optional[str],
        Field(
            example='/mdr/specializations/sdtm/packages/2022-10-26/datasetspecializations/SYSBP/variables/VSSTRESU'
        ),
    ] = None
    title: Annotated[Optional[str], Field(example='VSSTRESU (SYSPB)')] = None
    type: Annotated[
        Optional[str], Field(example='SDTM Dataset Specialization Variable')
    ] = None


class SdtmDatasetSpecializationVariableLinks(BaseModel):
    self: Optional[SdtmDatasetSpecializationVariableRef] = None
    DatasetSpecialization: Optional[SdtmDatasetSpecializationRef] = None
    parentPackage: Optional[SdtmPackageRef] = None


class MdrProductsProductGroupGet200ApplicationJsonResponse(
    ProductGroupDataCollection,
    ProductGroupIntegrated,
    ProductGroupDataTabulation,
    ProductGroupDataAnalysis,
    ProductGroupTerminology,
    ProductgroupQrsInstrument,
    ProductGroupDraftContent,
):
    pass


class MdrProductsProductGroupGet200ApplicationXmlResponse(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class MdrProductsProductGroupGet200TextCsvResponse(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class MdrProductsProductGroupGet200ApplicationVndOpenxmlformatsOfficedocumentS(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class MdrProductsProductGroupGet200ApplicationVndMsExcelResponse(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class MdrProductsProductGroupGet200ApplicationOdmXmlResponse(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class MdrProductsProductGroupGet200ApplicationGzipResponse(
    MdrProductsProductGroupGet200ApplicationJsonResponse
):
    pass


class FieldLinks11(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    valuelist: Optional[ValuelistRef] = None
    parentProduct: Optional[ProductRef] = None
    parentClass: Optional[ClassRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None
    sdtmClassMappingTargets: Annotated[
        Optional[List[VariableRef]], Field(description='SDTM Mapping Target Variables')
    ] = None
    sdtmDatasetMappingTargets: Annotated[
        Optional[List[VariableRef]], Field(description='SDTM Mapping Target Variables')
    ] = None


class CdashModelField(CdashModelFieldAttributes):
    field_links: Annotated[Optional[FieldLinks11], Field(alias='_links')] = None


class CdashClass(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks12], Field(alias='_links')] = None
    cdashModelFields: Annotated[
        Optional[List[CdashModelField]], Field(description='CDASH Model Fields')
    ] = None


class FieldLinks15(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    parentProduct: Optional[ProductRef] = None
    parentDomain: Optional[DomainRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None
    sdtmDatasetMappingTargets: Annotated[
        Optional[List[VariableRef]], Field(description='SDTM Mapping Target Variables')
    ] = None
    sdtmigDatasetMappingTargets: Annotated[
        Optional[List[VariableRef]],
        Field(description='SDTMIG Mapping Target Variables'),
    ] = None


class CdashField(CdashFieldAttributes):
    core: Annotated[Optional[str], Field(description='Core Classifier')] = None
    field_links: Annotated[Optional[FieldLinks15], Field(alias='_links')] = None


class FieldLinks21(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    valuelist: Optional[ValuelistRef] = None
    modelField: Optional[FieldRef] = None
    parentProduct: Optional[ProductRef] = None
    parentDomain: Optional[DomainRef] = None
    parentScenario: Optional[ScenarioRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None
    sdtmClassMappingTargets: Annotated[
        Optional[List[VariableRef]], Field(description='SDTM Mapping Target Variables')
    ] = None
    sdtmigDatasetMappingTargets: Annotated[
        Optional[List[VariableRef]],
        Field(description='SDTMIG Mapping Target Variables'),
    ] = None


class CdashigField(CdashFieldAttributes):
    core: Annotated[Optional[str], Field(description='Core Classifier')] = None
    field_links: Annotated[Optional[FieldLinks21], Field(alias='_links')] = None


class FieldLinks22(BaseModel):
    self: Optional[Link] = None
    codelist: Optional[CodelistRef] = None
    valuelist: Optional[ValuelistRef] = None
    modelField: Optional[FieldRef] = None
    parentProduct: Optional[ProductRef] = None
    parentDomain: Optional[DomainRef] = None
    parentScenario: Optional[ScenarioRef] = None
    rootItem: Optional[RootItemRef] = None
    priorVersion: Optional[PriorVersion] = None
    sdtmigDatasetMappingTargets: Annotated[
        Optional[List[VariableRef]],
        Field(description='SDTMIG Mapping Target Variables'),
    ] = None


class CdashigScenarioField(CdashFieldAttributes):
    core: Annotated[Optional[str], Field(description='Core Classifier')] = None
    field_links: Annotated[Optional[FieldLinks22], Field(alias='_links')] = None


class CdashigDomain(CdashigDomainAttributes):
    field_links: Annotated[Optional[FieldLinks23], Field(alias='_links')] = None
    fields: Annotated[
        Optional[List[CdashigField]], Field(description='Domain Fields')
    ] = None


class CdashigScenario(CdashigScenarioAttributes):
    field_links: Annotated[Optional[FieldLinks25], Field(alias='_links')] = None
    fields: Annotated[
        Optional[List[CdashigScenarioField]], Field(description='CDASHIG Fields')
    ] = None


class CdashigClass(ClassAttributes):
    field_links: Annotated[Optional[FieldLinks27], Field(alias='_links')] = None
    domains: Annotated[Optional[List[CdashigDomain]], Field(description='Domains')] = (
        None
    )
    scenarios: Annotated[
        Optional[List[CdashigScenario]], Field(description='Scenarios')
    ] = None


class CdashigProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks30], Field(alias='_links')] = None
    classes: Annotated[Optional[List[CdashigClass]], Field(description='Classes')] = (
        None
    )


class ProductgroupQrsInstrumentLinks(BaseModel):
    self: Optional[ProductgroupRef] = None
    instruments: Optional[List[QrsInstrumentRefElement]] = None


class QrsInstrumentProductLinks(BaseModel):
    self: Optional[QrsInstrumentProductRef] = None
    priorVersion: Optional[QrsInstrumentProductRef] = None
    instrumentCAT: Optional[RootTermInstrumentCATRef] = None
    instrumentSCAT: Optional[RootTermInstrumentSCATRef] = None


class FieldLinks59(BaseModel):
    self: Optional[QrsInstrumentResponseGroupRef] = None
    parentInstrument: Optional[QrsInstrumentProductRef] = None


class QrsInstrumentResponseGroupResponseLinks(BaseModel):
    responseORRES: Optional[RootTermResponseORRESRef] = None
    responseSTRESC: Optional[RootTermResponseSTRESCRef] = None
    responseSTRESN: Optional[RootTermResponseSTRESNRef] = None


class FieldLinks60(BaseModel):
    self: Optional[QrsInstrumentResponseGroupsRef] = None
    parentInstrument: Optional[QrsInstrumentProductRef] = None
    responseGroups: Optional[List[QrsInstrumentResponseGroupRef]] = None


class QrsInstrumentResponseGroupsLinks(BaseModel):
    field_links: Annotated[Optional[FieldLinks60], Field(alias='_links')] = None


class FieldLinks61(BaseModel):
    self: Optional[QrsInstrumentItemsRef] = None
    parentInstrument: Optional[QrsInstrumentProductRef] = None
    items: Optional[List[QrsInstrumentItemRef]] = None


class QrsInstrumentItemsLinks(BaseModel):
    field_links: Annotated[Optional[FieldLinks61], Field(alias='_links')] = None


class QrsInstrumentItemLink(BaseModel):
    self: Optional[QrsInstrumentItemRef] = None
    parentInstrument: Optional[QrsInstrumentProductRef] = None
    instrumentItemTESTCD: Optional[RootTermInstrumentItemTESTCDRef] = None
    instrumentItemTEST: Optional[RootTermInstrumentItemTESTRef] = None


class FieldLinks65(BaseModel):
    self: Optional[Link] = None
    data_collection: Annotated[
        Optional[ProductDataCollection], Field(alias='data-collection')
    ] = None
    data_tabulation: Annotated[
        Optional[ProductDataTabulation], Field(alias='data-tabulation')
    ] = None
    data_analysis: Annotated[
        Optional[ProductDataAnalysis], Field(alias='data-analysis')
    ] = None
    qrs: Optional[ProductQrsInstrument] = None
    draft_content: Annotated[
        Optional[ProductDraftContent], Field(alias='draft-content')
    ] = None
    integrated: Optional[ProductIntegrated] = None
    terminology: Optional[ProductTerminology] = None


class Products(BaseModel):
    field_links: Annotated[Optional[FieldLinks65], Field(alias='_links')] = None


class UseCaseList(BaseModel):
    field_links: Annotated[Optional[FieldLinks76], Field(alias='_links')] = None
    useCases: Optional[List[UseCase]] = None


class UseCaseSectionsList(BaseModel):
    field_links: Annotated[Optional[FieldLinks76], Field(alias='_links')] = None
    useCaseSections: Optional[List[SectionsListForUsecaseAndStandard]] = None


class BcPackagesLinks(BaseModel):
    self: Optional[BcPackagesRef] = None
    packages: Optional[List[BcPackageRef]] = None


class BcBiomedicalConceptsLinks(BaseModel):
    self: Optional[BcBiomedicalConceptsRef] = None
    biomedicalConcepts: Optional[List[BcBiomedicalConceptRef]] = None


class BcBiomedicalConceptLinks(BaseModel):
    self: Optional[BcBiomedicalConceptRef] = None
    parentBiomedicalConcept: Optional[BcBiomedicalConceptParentRef] = None
    parentPackage: Optional[BcPackageRef] = None


class BcDataElementConceptsLinks(BaseModel):
    self: Optional[BcDataElementConceptsRef] = None
    parentBiomedicalConcept: Optional[BcBiomedicalConceptParentRef] = None
    parentPackage: Optional[BcPackageRef] = None
    dataElementConcepts: Optional[List[BcDataElementConceptRef]] = None


class BcDataElementConcept(BaseModel):
    conceptId: Annotated[str, Field(example='C123975')]
    href: Annotated[
        Optional[AnyUrl],
        Field(
            example='https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C123975'
        ),
    ] = None
    label: Annotated[str, Field(example='Vital Signs Laterality')]
    dataType: Annotated[Optional[str], Field(example='string')] = None
    exampleSet: Annotated[Optional[List[str]], Field(example=['Left', 'Right'])] = None
    field_links: Annotated[
        Optional[BcDataElementConceptLinks], Field(alias='_links')
    ] = None


class SdtmPackagesLinks(BaseModel):
    self: Optional[SdtmPackagesRef] = None
    packages: Optional[List[SdtmPackageRef]] = None


class SdtmDatasetSpecializationsLinks(BaseModel):
    self: Optional[SdtmDatasetSpecializationsRef] = None
    DatasetSpecializations: Optional[List[SdtmDatasetSpecializationRef]] = None


class SdtmDatasetSpecializationLinks(BaseModel):
    self: Optional[SdtmDatasetSpecializationRef] = None
    parentBiomedicalConcept: Optional[SdtmBiomedicalConceptRef] = None
    parentPackage: Optional[SdtmPackageRef] = None


class SdtmDatasetSpecializationVariableElement(BaseModel):
    name: Annotated[str, Field(example='VSSTRESU')]
    dataElementConceptId: Annotated[Optional[str], Field(example='C49669')] = None
    isNonStandard: Optional[bool] = False
    codelist: Optional[SdtmDatasetSpecializationCodeList] = None
    subsetCodelist: Annotated[Optional[str], Field(example='XYZ')] = None
    valueList: Annotated[Optional[List[str]], Field(example=['ABC', 'DEF'])] = None
    assignedTerm: Optional[SdtmDatasetpecializationAssignedTerm] = None
    role: Annotated[Optional[str], Field(example='Qualifier')] = None
    dataType: Annotated[Optional[str], Field(example='string')] = None
    length: Annotated[Optional[int], Field(example=20)] = None
    format: Optional[str] = None
    significantDigits: Optional[int] = None
    relationship: Optional[SdtmDatasetpecializationRelationship] = None
    mandatoryVariable: Optional[bool] = False
    mandatoryValue: Optional[bool] = False
    originType: Annotated[Optional[str], Field(example='Assigned')] = None
    originSource: Annotated[Optional[str], Field(example='Sponsor')] = None
    comparator: Optional[str] = None
    vlmTarget: Annotated[Optional[bool], Field(example=True)] = False


class SdtmDatasetSpecializationVariablesLinks(BaseModel):
    self: Optional[SdtmDatasetSpecializationVariablesRef] = None
    parentDatasetSpecialization: Optional[SdtmDatasetSpecializationRef] = None
    parentBiomedicalConcept: Optional[SdtmBiomedicalConceptRef] = None
    parentPackage: Optional[SdtmPackageRef] = None
    variables: Optional[List[SdtmDatasetSpecializationVariableRef]] = None


class SdtmDatasetSpecializationVariable(BaseModel):
    name: Annotated[str, Field(example='VSSTRESU')]
    dataElementConceptId: Annotated[Optional[str], Field(example='C49669')] = None
    isNonStandard: Optional[bool] = False
    codelist: Optional[SdtmDatasetSpecializationCodeList] = None
    subsetCodelist: Annotated[Optional[str], Field(example=['XYZ'])] = None
    valueList: Annotated[Optional[List[str]], Field(example=['ABC', 'DEF'])] = None
    assignedTerm: Optional[SdtmDatasetpecializationAssignedTerm] = None
    role: Annotated[Optional[str], Field(example='Qualifier')] = None
    dataType: Annotated[Optional[str], Field(example='string')] = None
    length: Annotated[Optional[int], Field(example=20)] = None
    format: Optional[str] = None
    significantDigits: Optional[int] = None
    relationship: Optional[SdtmDatasetpecializationRelationship] = None
    mandatoryVariable: Optional[bool] = False
    mandatoryValue: Optional[bool] = False
    originType: Annotated[Optional[str], Field(example='Assigned')] = None
    originSource: Annotated[Optional[str], Field(example='Sponsor')] = None
    comparator: Optional[str] = None
    vlmTarget: Annotated[Optional[bool], Field(example=True)] = False
    field_links: Annotated[
        Optional[SdtmDatasetSpecializationVariableLinks], Field(alias='_links')
    ] = None


class CdashDomain(CdashDomainAttributes):
    field_links: Annotated[Optional[FieldLinks14], Field(alias='_links')] = None
    fields: Annotated[
        Optional[List[CdashField]], Field(description='Domain Fields')
    ] = None


class XmlProducts(BaseModel):
    self: Optional[Products] = None


class QrsInstrumentResponseGroupResponse(BaseModel):
    field_links: Annotated[
        Optional[QrsInstrumentResponseGroupResponseLinks], Field(alias='_links')
    ] = None
    ordinal: Annotated[Optional[int], Field(example=1)] = None
    isStandardResultNumeric: Annotated[Optional[bool], Field(example=True)] = None


class BcPackages(BaseModel):
    field_links: Annotated[Optional[BcPackagesLinks], Field(alias='_links')] = None


class BcBiomedicalConcepts(BaseModel):
    name: Annotated[Optional[str], Field(example='Biomedical Concepts 2022-10-26')] = (
        None
    )
    label: Annotated[
        Optional[str], Field(example='Biomedical Concept Package Effective 2022-10-26')
    ] = None
    effectiveDate: Annotated[Optional[str], Field(example='2022-10-26')] = None
    version: Annotated[Optional[str], Field(example='2022-10-26')] = None
    field_links: Annotated[
        Optional[BcBiomedicalConceptsLinks], Field(alias='_links')
    ] = None


class BcBiomedicalConcept(BaseModel):
    conceptId: Annotated[str, Field(example='C49676')]
    href: Annotated[
        Optional[AnyUrl],
        Field(
            example='https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C49676'
        ),
    ] = None
    category: Annotated[List[str], Field(example=['Vital Signs'])]
    shortName: Annotated[str, Field(example='Pulse Rate')]
    synonym: Annotated[Optional[List[str]], Field(example=['Pulse'])] = None
    resultScale: Annotated[Optional[ResultScale], Field(example='Quantitative')] = None
    definition: Annotated[
        str,
        Field(
            example='The rate of the pulse as observed in an artery, expressed as beats per minute. It can be measured at several anatomic sites, including the wrist, neck, temple, groin, behind the knees, or on top of the foot.'
        ),
    ]
    coding: Optional[List[BcBiomedicalConceptCoding]] = None
    field_links: Annotated[
        Optional[BcBiomedicalConceptLinks], Field(alias='_links')
    ] = None
    dataElementConcepts: Optional[List[BcDataElementConceptElement]] = None


class BcDataElementConcepts(BaseModel):
    conceptId: Annotated[str, Field(example='C49676')]
    href: Annotated[
        Optional[AnyUrl],
        Field(
            example='https://ncithesaurus.nci.nih.gov/ncitbrowser/ConceptReport.jsp?dictionary=NCI_Thesaurus&ns=ncit&code=C49676'
        ),
    ] = None
    category: Annotated[List[str], Field(example=['Vital Signs'])]
    shortName: Annotated[str, Field(example='Pulse Rate')]
    synonym: Annotated[Optional[List[str]], Field(example=['Pulse'])] = None
    resultScale: Annotated[Optional[ResultScale], Field(example='Quantitative')] = None
    definition: Annotated[
        str,
        Field(
            example='The rate of the pulse as observed in an artery, expressed as beats per minute. It can be measured at several anatomic sites, including the wrist, neck, temple, groin, behind the knees, or on top of the foot.'
        ),
    ]
    coding: Optional[List[BcBiomedicalConceptCoding]] = None
    field_links: Annotated[
        Optional[BcDataElementConceptsLinks], Field(alias='_links')
    ] = None


class SdtmPackages(BaseModel):
    field_links: Annotated[Optional[SdtmPackagesLinks], Field(alias='_links')] = None


class SdtmDatasetSpecializations(BaseModel):
    name: Annotated[
        Optional[str], Field(example='SDTM Dataset Specializations 2022-10-26')
    ] = None
    label: Annotated[
        Optional[str],
        Field(example='SDTM Dataset Specialization Package Effective 2022-10-26'),
    ] = None
    effectiveDate: Annotated[Optional[str], Field(example='2022-10-26')] = None
    version: Annotated[Optional[str], Field(example='2022-10-26')] = None
    field_links: Annotated[
        Optional[SdtmDatasetSpecializationsLinks], Field(alias='_links')
    ] = None


class SdtmDatasetSpecialization(BaseModel):
    datasetSpecializationId: Annotated[str, Field(example='SYSBP')]
    domain: Annotated[str, Field(example='VS')]
    shortName: Annotated[str, Field(example='Systolic Blood Pressure')]
    source: Annotated[str, Field(example='VS.VSTESTCD')]
    sdtmigStartVersion: Annotated[Optional[str], Field(example='3-2')] = None
    sdtmigEndVersion: Annotated[Optional[str], Field(example='3-4')] = None
    field_links: Annotated[
        Optional[SdtmDatasetSpecializationLinks], Field(alias='_links')
    ] = None
    variables: Optional[List[SdtmDatasetSpecializationVariableElement]] = None


class SdtmDatasetSpecializationVariables(BaseModel):
    datasetSpecializationId: Annotated[str, Field(example='SYSBP')]
    domain: Annotated[str, Field(example='VS')]
    shortName: Annotated[str, Field(example='Systolic Blood Pressure')]
    source: Annotated[str, Field(example='VS.VSTESTCD')]
    sdtmigStartVersion: Annotated[Optional[str], Field(example='3-2')] = None
    sdtmigEndVersion: Annotated[Optional[str], Field(example='3-4')] = None
    field_links: Annotated[
        Optional[SdtmDatasetSpecializationVariablesLinks], Field(alias='_links')
    ] = None


class CdashProduct(ProductAttributes):
    field_links: Annotated[Optional[FieldLinks13], Field(alias='_links')] = None
    classes: Annotated[Optional[List[CdashClass]], Field(description='Classes')] = None
    domains: Annotated[Optional[List[CdashDomain]], Field(description='Domains')] = None


class QrsInstrumentResponseGroupResponses(BaseModel):
    __root__: List[QrsInstrumentResponseGroupResponse]


class QrsInstrumentResponseGroup(BaseModel):
    field_links: Annotated[Optional[FieldLinks59], Field(alias='_links')] = None
    name: Annotated[Optional[str], Field(example='AIMS01-01 to 07')] = None
    label: Annotated[Optional[str], Field(example='AIMS:VD.AIMS01-01 to 07')] = None
    responseType: Annotated[Optional[str], Field(example='Verbal Rating Scale')] = None
    responses: Optional[QrsInstrumentResponseGroupResponses] = None


class QrsInstrumentResponseGroups(BaseModel):
    __root__: List[QrsInstrumentResponseGroup]


class QrsInstrumentItem(BaseModel):
    field_links: Annotated[Optional[QrsInstrumentItemLink], Field(alias='_links')] = (
        None
    )
    ordinal: Annotated[Optional[int], Field(example=1)] = None
    label: Annotated[
        Optional[str],
        Field(
            example='Abnormal Involuntary Movement Scale - Facial and Oral Movements, Muscles of facial expression, e.g., movements of forehead, eyebrows, periorbital area, cheeks. Include frowning, blinking, grimacing of upper face.'
        ),
    ] = None
    questionText: Annotated[
        Optional[str], Field(example='AIMS01-Muscles of Facial Expression')
    ] = None
    itemCode: Annotated[Optional[str], Field(example='AIMS0101')] = None
    responseGroup: Optional[QrsInstrumentResponseGroup] = None


class QrsInstrumentItems(BaseModel):
    __root__: List[QrsInstrumentItem]


class QrsInstrument(BaseModel):
    field_links: Annotated[
        Optional[QrsInstrumentProductLinks], Field(alias='_links')
    ] = None
    name: Annotated[Optional[str], Field(example='AIMS01 v1.0')] = None
    label: Annotated[
        Optional[str], Field(example='Abnormal Involuntary Movement Scale Version 1.0')
    ] = None
    description: Annotated[
        Optional[str],
        Field(
            example='Abnormal Involuntary Movement Scale (AIMS) (Guy W. Ed. ECDEU Assessment Manual for Psychopharmacology. Rockville MD: US Dept of Health, Education and Welfare. 1976, Publication No. (ADM) 76-338).'
        ),
    ] = None
    effectiveDate: Annotated[Optional[str], Field(example='2013-05-22')] = None
    untilDate: Annotated[Optional[str], Field(example='2022-12-31')] = None
    registrationStatus: Annotated[Optional[str], Field(example='Final')] = None
    version: Annotated[Optional[str], Field(example='1.0')] = None
    instrumentType: Annotated[Optional[str], Field(example='Questionnaire')] = None
    copyrightStatus: Annotated[Optional[str], Field(example='Public Domain')] = None
    responseGroups: Optional[QrsInstrumentResponseGroups] = None
    items: Optional[QrsInstrumentItems] = None


Condition.update_forward_refs()
