# generated by datamodel-codegen:
#   filename:  cm_variables.json
#   timestamp: 2024-08-16T17:13:09+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field


class DatasetVariable(BaseModel):
    href: str
    title: str
    type: str


class ParentClass(BaseModel):
    href: str
    title: str
    type: str


class ParentProduct(BaseModel):
    href: str
    title: str
    type: str


class PriorVersion(BaseModel):
    href: str
    title: str
    type: str


class Self(BaseModel):
    href: str
    title: str
    type: str


class FieldLinks(BaseModel):
    datasetVariables: List[DatasetVariable]
    parentClass: ParentClass
    parentProduct: ParentProduct
    priorVersion: PriorVersion
    self: Self


class Model(BaseModel):
    field_links: FieldLinks = Field(..., alias='_links')
    datasetStructure: str
    description: str
    label: str
    name: str
    ordinal: str
